version: "3.8"
services:
  # mongodb:
  #   image: 'mongo'
  #   volumes:
  #     - data:/data/db
  auth:
    build: ./auth
    stdin_open: true
    tty: true
    env_file:
      - ./env/secret.env
    ports: 
      - '8000:8000'
  product:
    build: ./products
    stdin_open: true
    tty: true
    env_file:
      - ./env/secret.env
    ports: 
      - '8001:8001'
  # client:
  #   build: ./client
  #   stdin_open: true
  #   tty: true
  #   ports: 
  #     - '3003:3003'
  order:
    build: ./orders
    stdin_open: true
    tty: true
    env_file:
      - ./env/secret.env
    ports:
      - '8002:8002'

  # client:
