version: "3.8"
services:
  # mongodb:
  #   image: 'mongo'
  #   volumes:
  #     - data:/data/db
  auth:
    build: ./auth
    stdin_open: true
    tty: true
    env_file:
      - ./env/secret.env
    ports: 
      - '8080:8080'
  product:
    build: ./products
    stdin_open: true
    tty: true
    env_file:
      - ./env/secret.env
    ports: 
      - '8081:8081'
  # client:
